#ifndef __CSJRESOURCEIDENTIFIERS_H__
#define __CSJRESOURCEIDENTIFIERS_H__

typedef enum {
    CSJBUTTONID_PLAY = 1,
    CSJBUTTONID_STOP,
    CSJBUTTONID_PAUSE,
    CSJBUTTONID_RESUME,
    CSJBUTTONID_FASTFORWARD,
    CSJBUTTONID_FASTBACKWARD
} CSJButtonID;

 #endif // __CSJRESOURCEIDENTIFIERS_H__